# Generated by Django 4.2.5 on 2025-09-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this item file has been downloaded'),
        ),
    ]
