# Generated by Django 4.2.5 on 2025-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='pano_id',
            field=models.CharField(default='unknown', help_text="ID used for panoramic view and React routing (matches JSON 'panoId')", max_length=100),
            preserve_default=False,
        ),
    ]
