# Generated by Django 4.2.5 on 2025-09-04

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("core", "0002_monastery_pano_id"),
	]

	operations = [
		# This migration was accidentally left empty. Keep as a no-op to maintain
		# migration history integrity.
	]
