# Generated by Django 4.2.5 on 2025-09-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_monastery_pano_id'),
    ]

    operations = [
    ]
