# Generated by Django 4.2.5 on 2025-09-01 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this panoramic view', max_length=200)),
                ('description', models.TextField(help_text='Description of what this panorama shows')),
                ('location_name', models.CharField(help_text="Name of the specific location (e.g., 'Main Hall', 'Courtyard')", max_length=200)),
                ('image', models.ImageField(help_text='360-degree panoramic image file', upload_to='tours/panoramas/')),
                ('image_alt', models.CharField(help_text='Alt text for the panoramic image (accessibility)', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for preview', upload_to='tours/thumbnails/')),
                ('narration_audio', models.FileField(blank=True, help_text='Audio narration for this panorama', upload_to='tours/audio/')),
                ('audio_duration', models.PositiveIntegerField(blank=True, help_text='Duration of audio narration in seconds', null=True)),
                ('audio_transcript', models.TextField(blank=True, help_text='Text transcript of audio narration (accessibility)')),
                ('initial_yaw', models.FloatField(default=0.0, help_text='Initial horizontal angle in degrees')),
                ('initial_pitch', models.FloatField(default=0.0, help_text='Initial vertical angle in degrees')),
                ('hotspots_data', models.JSONField(blank=True, default=dict, help_text='JSON data for interactive hotspots within the panorama')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the monastery tour')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to feature this panorama')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this panorama is active')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this panorama has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monastery', models.ForeignKey(help_text='The monastery this panorama belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='core.monastery')),
            ],
            options={
                'ordering': ['monastery', 'order', 'title'],
                'unique_together': {('monastery', 'location_name')},
            },
        ),
    ]
