# Generated by Django 4.2.5 on 2025-09-01 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the primary visitor', max_length=100)),
                ('email', models.EmailField(help_text='Email address for confirmation and communication', max_length=254)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('visit_date', models.DateField(help_text='Preferred date for the visit')),
                ('visit_time', models.TimeField(blank=True, help_text='Preferred time for the visit (if specific time needed)', null=True)),
                ('visit_type', models.CharField(choices=[('general', 'General Visit'), ('guided_tour', 'Guided Tour'), ('meditation', 'Meditation Session'), ('photography', 'Photography Session'), ('research', 'Research/Academic'), ('group_visit', 'Group Visit'), ('special_event', 'Special Event'), ('volunteer', 'Volunteer Work'), ('other', 'Other')], default='general', help_text='Type of visit requested', max_length=20)),
                ('number_of_visitors', models.PositiveIntegerField(default=1, help_text='Total number of people in the group', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('number_of_adults', models.PositiveIntegerField(default=1, help_text='Number of adults in the group')),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='Number of children in the group')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or accessibility needs')),
                ('purpose_of_visit', models.TextField(blank=True, help_text='Purpose or reason for the visit')),
                ('preferred_language', models.CharField(default='English', help_text='Preferred language for communication', max_length=50)),
                ('organization', models.CharField(blank=True, help_text='Organization or institution name (if group visit)', max_length=200)),
                ('group_leader', models.CharField(blank=True, help_text='Group leader name (if different from primary contact)', max_length=100)),
                ('transportation_needed', models.BooleanField(default=False, help_text='Whether transportation assistance is needed')),
                ('accommodation_needed', models.BooleanField(default=False, help_text='Whether accommodation recommendations are needed')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('confirmation_number', models.CharField(blank=True, help_text='Unique confirmation number for the booking', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for monastery staff')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder has been sent')),
                ('feedback_requested', models.BooleanField(default=False, help_text='Whether feedback has been requested post-visit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monastery', models.ForeignKey(help_text='The monastery being visited', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.monastery')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['visit_date'], name='bookings_bo_visit_d_59119e_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'), models.Index(fields=['monastery', 'visit_date'], name='bookings_bo_monaste_584311_idx')],
            },
        ),
    ]
