# Generated by Django 4.2.5 on 2025-09-08 15:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('event', 'Event Booking'), ('tour', 'Tour Booking')], default='event', help_text='Type of booking', max_length=10)),
                ('customer_name', models.CharField(help_text='Full name of the customer', max_length=100)),
                ('customer_email', models.EmailField(help_text='Email address for confirmation', max_length=254)),
                ('customer_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('number_of_people', models.PositiveIntegerField(default=1, help_text='Number of people for this booking', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('number_of_adults', models.PositiveIntegerField(default=1, help_text='Number of adults')),
                ('number_of_children', models.PositiveIntegerField(default=0, help_text='Number of children')),
                ('special_requirements', models.TextField(blank=True, help_text='Any special requirements or dietary restrictions')),
                ('accessibility_needs', models.TextField(blank=True, help_text='Any accessibility requirements')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total booking amount', max_digits=10)),
                ('currency', models.CharField(default='INR', help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Confirmed'), ('confirmed', 'Booking Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=50)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID', max_length=100)),
                ('confirmation_number', models.CharField(blank=True, help_text='Unique booking confirmation number', max_length=20, unique=True)),
                ('booking_notes', models.TextField(blank=True, help_text='Additional notes from customer')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when payment was confirmed', null=True)),
                ('event', models.ForeignKey(help_text='The event being booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='bookings_ev_event_i_9323d9_idx'), models.Index(fields=['payment_status'], name='bookings_ev_payment_e96467_idx'), models.Index(fields=['confirmation_number'], name='bookings_ev_confirm_fb91cf_idx')],
            },
        ),
    ]
