# Generated by Django 4.2.5 on 2025-09-09 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bookings',
                to=settings.AUTH_USER_MODEL,
                help_text="User who made this booking"
            ),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='event_bookings',
                to=settings.AUTH_USER_MODEL,
                help_text="User who made this booking"
            ),
        ),
    ]
