name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:13-3.1
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: monastery360_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev libproj-dev libgeos-dev

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting
        run: |
          flake8 .

      - name: Run tests
        env:
          DATABASE_URL: postgis://postgres:postgres@localhost:5432/monastery360_test
          SECRET_KEY: test-secret-key
          DEBUG: True
        run: |
          python manage.py collectstatic --noinput
          python manage.py migrate
          python manage.py test

      - name: Check migrations
        env:
          DATABASE_URL: postgis://postgres:postgres@localhost:5432/monastery360_test
          SECRET_KEY: test-secret-key
        run: |
          python manage.py makemigrations --check --dry-run
